### ISSUE TITLE
Add Templates support

### ISSUE THREAD

**Issue by arbfay** [pastjean/postmark-rs#1]
Hey, it's a great crate! Congrats on this 💯 

I'm using the crate, and now am wondering how to use [Postmark's templates](https://postmarkapp.com/developer/api/templates-api). Unfortunately, it's not yet supported by this client. 

So, first github issue: can we add support for templates?

**Comment by pastjean** [comment]
Yeah, Seems pretty simple. If you wanna try your hand at it go ahead otherwise i'll do that over the week and post a new version afterwards
