### ISSUE TITLE
send_email_with_template appears gone?

### ISSUE THREAD

**Issue by nipunn1313** [pastjean/postmark-rs#20]
See comment here:
https://github.com/pastjean/postmark-rs/pull/13/files#r1314417921

I tried this code:

```rust
let req = SendEmailWithTemplateRequest::builder();
```

I expected to see this happen: exists/compiles

Instead, this happened:
```
 --> crates/emailer/src/lib.rs:6:9
  |
6 |         SendEmailWithTemplateRequest,
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `SendEmailWithTemplateRequest` in `api::email`
7 |         TemplateModel,
  |         ^^^^^^^^^^^^^ no `TemplateModel` in `api::email`
```

I think the ability to send emails with templates was removed, possibly by accident? Seems like the file with the code is there, but the `mod` and `pub use` lines were removed.

**Comment by kingledion** [comment]
I broke that, I apologize. This should fix it: https://github.com/pastjean/postmark-rs/pull/21, if you would like to merge it in @pastjean.

**Comment by pastjean** [comment]
Yeah I'll merge it and release a new version with the fix.

**Comment by pastjean** [comment]
0.9.1 should have the fix in. It'll be available in a couple of minutes.

Sorry for having missed that
