### ISSUE TITLE
SendEmailRequest: Support supplying both TextBody and HtmlBody

### ISSUE THREAD

**Issue by VojtaStanek** [pastjean/postmark-rs#5]
Currently SendEmailRequest::body setter supports setting either HTML body or text body, but not both for a single email. Setting both is supported by Postmark API - [see example here](https://postmarkapp.com/developer/api/email-api#send-a-single-email).

**Comment by pastjean** [comment]
Here you go, that's now available in 0.7

**Comment by VojtaStanek** [comment]
Thanks a lot, that was fast!
