### ISSUE TITLE
Templates API

### ISSUE THREAD

**Issue by kingledion** [pastjean/postmark-rs#8]
Is anyone working on the templates API? (https://postmarkapp.com/developer/api/templates-api)

If not, I believe I have a use case for that and would take a stab at it over the next couple of weeks.

**Comment by pastjean** [comment]
I'd be happy to accept this patch in. I'm currently not working much on this implementation

**Comment by pastjean** [comment]
Just realized, We've got this `https://github.com/pastjean/postmark-rs/blob/main/src/api/email/send_email_with_template.rs` in the library, it might need some work, but I believe it's part of the templates API

**Comment by kingledion** [comment]
I see that in there! I've already started working on Create Templates endpoint. 

I was thinking of moving that "Send email with template" to the `templates` module that I am making in order to match the PostMark API divisions: https://postmarkapp.com/developer/api/email-api#send-a-single-email.

**Comment by pastjean** [comment]
Ahh all right so you mean the other templates endpoint! Great then!

**Comment by pastjean** [comment]
fixed by #15, #16 & #17
